### ISSUE TITLE
Batches are always shuffled the same way

### ISSUE THREAD

**Issue by yoptar** [deepmipt/Pilot#13]
https://github.com/deepmipt/Pilot/blob/5148296f1e4b296849298f5dece670968e0c49f8/deeppavlov/core/data/dataset.py#L71-L78
`self.seed` newer changes, so shuffling is always the same. I propose to merge [my pull request](https://github.com/deepmipt/Pilot/pull/9) to fix this

**Comment by my-master** [comment]
merged
