### ISSUE TITLE
USR_DIR location relative to the config_path

### ISSUE THREAD

**Issue by yoptar** [deepmipt/Pilot#6]
https://github.com/deepmipt/Pilot/blob/111a45c9d68d288677d13e1a2ff0d0af4d1f2fe6/deeppavlov/core/commands/utils.py#L15-L17
`Path(config_path).cwd()` is equal to `Path.cwd()` and will return current working directory, so it's not clear why `config path` is used there or why `.cwd()` method is called

**Comment by my-master** [comment]
resolved
